export enum ENVIRONMENT {
  LOCAL = "local",
  DEVELOPMENT = "development",
  PRODUCTION = "production",
}

type Env = {
  PORT: number;
  JWT_SECRET?: string;
  JWT_REFRESH_SECRET?: string;
  GOOGLE_CLIENT_ID?: string;
  MYCOVE_GOOGLE_CLIENT_ID?: string;
  DATABASE_URL?: string;
  CLOUDINARY_CLOUD_NAME?: string;
  CLOUDINARY_API_KEY?: string;
  CLOUDINARY_API_SECRET?: string;

  FIREBASE_PROJECT_ID?: string;
  FIREBASE_PRIVATE_KEY?: string;
  FIREBASE_CLIENT_EMAIL?: string;
  MYCOVE_FIREBASE_PROJECT_ID?: string;
  MYCOVE_FIREBASE_PRIVATE_KEY?: string;
  MYCOVE_FIREBASE_CLIENT_EMAIL?: string;
  ABLY_API_KEY?: string;
  GEMINI_API_KEY?: string;
  REVENUECAT_REST_API_KEY?: string;
  REVENUECAT_ENTITLEMENT_ID?: string;
  REVENUECAT_WEBHOOK_SECRET?: string;
  MYCOVE_REVENUECAT_REST_API_KEY?: string;
  MYCOVE_REVENUECAT_ENTITLEMENT_ID?: string;
  MYCOVE_REVENUECAT_WEBHOOK_SECRET?: string;
  ENVIRONMENT: ENVIRONMENT;
};

export const Env: Env = {
  PORT: Number(process.env.PORT) || 4000,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  MYCOVE_GOOGLE_CLIENT_ID: process.env.MYCOVE_GOOGLE_CLIENT_ID,
  DATABASE_URL: process.env.DATABASE_URL,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,

  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
  FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
  MYCOVE_FIREBASE_PROJECT_ID: process.env.MYCOVE_FIREBASE_PROJECT_ID,
  MYCOVE_FIREBASE_PRIVATE_KEY: process.env.MYCOVE_FIREBASE_PRIVATE_KEY,
  MYCOVE_FIREBASE_CLIENT_EMAIL: process.env.MYCOVE_FIREBASE_CLIENT_EMAIL,

  ABLY_API_KEY: process.env.ABLY_API_KEY,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  REVENUECAT_REST_API_KEY: process.env.REVENUECAT_REST_API_KEY,
  REVENUECAT_ENTITLEMENT_ID: process.env.REVENUECAT_ENTITLEMENT_ID,
  REVENUECAT_WEBHOOK_SECRET: process.env.REVENUECAT_WEBHOOK_SECRET,
  MYCOVE_REVENUECAT_REST_API_KEY:
    process.env.MYCOVE_REVENUECAT_REST_API_KEY,
  MYCOVE_REVENUECAT_ENTITLEMENT_ID:
    process.env.MYCOVE_REVENUECAT_ENTITLEMENT_ID,
  MYCOVE_REVENUECAT_WEBHOOK_SECRET:
    process.env.MYCOVE_REVENUECAT_WEBHOOK_SECRET,

  ...(process.env as any),
};
